### ISSUE TITLE
Fedora 38, failed to build wheel for Pillow (jpeg headers missing)

### ISSUE THREAD

**Issue by RedBearAK** [Nyre221/dolphin-quick-view#1]
@Nyre221 

FYI: 

On a Fedora 38 KDE spin in a Boxes virtual machine, I needed to install `libjpeg-devel`, which actually installed `libjpeg-turbo-devel`, to get past an error building the wheel for Pillow, during the `pip install textract` step of the instructions from the Pling page for setting up requirements. 

Also, if this works well and it looks like you're going to maintain it, I may integrate the installation of this into the optional steps taken by my own project when installing on KDE: 

https://github.com/RedBearAK/toshy

The purpose of Toshy is to make it easy to install a keymapper setup to make the keyboard in Linux work like macOS, so having a Quick Look option for KDE would be fantastic. 

For my own project I had to move to using a full Python virtual environment to make it compatible with more distros, and you might want to look into that. Some distros have recently moved to using a "managed" Python environment, which means they discourage the use of `pip` to install packages, both at the system and the user level. And `pipx` kind of works to get around that, but is not necessarily a replacement for a project with numerous Python dependencies.

**Comment by Nyre221** [comment]
I've added dependencies to the list, thanks for letting me know.

> Also, if this works well and it looks like you're going to maintain it, I may integrate the installation of this into the optional steps taken by my own project when installing on KDE:

I intend to keep it updated and make the pyqt6 version when the time comes, but for now I have no plans to extend its functionality much.

> The purpose of Toshy is to make it easy to install a keymapper setup to make the keyboard in Linux work like macOS, so having a Quick Look option for KDE would be fantastic.

I'd be happy :)

To help with your project and mine we could look into having the dolphin developers add a custom shortcuts feature. When I can I will make a NEW feature proposal and forward it to you.
Currently there is already this if you are interested: https://bugs.kde.org/show_bug.cgi?id=260266

> For my own project I had to move to using a full Python virtual environment

I was also thinking that maybe I could use appimage and flatpak to remedy this problem, but I need time since I have no idea how this stuff works.

with the virtual environment there would still be dependencies to install via apt, dnf, etc, and I don't know if in my case it is the best solution (probably the easiest).

Thanks again!

**Comment by RedBearAK** [comment]
@Nyre221 

> I intend to keep it updated and make the pyqt6 version when the time comes, but for now I have no plans to extend its functionality much.

Hey, have you looked at PySide6? I was making a simple image display app with PyQt5 a few months back and PySide6 was pretty much a drop-in replacement. I don't fully understand the whole Qt5/Qt6 situation, so I don't know if it would cause you any issues to jump on PySide6 already. But as far as I know it's complete and stable. 

> with the virtual environment there would still be dependencies to install via apt, dnf, etc, and I don't know if in my case it is the best solution (probably the easiest).

Yes, unfortunately there are still the various native packages that must be installed. With my own project I set up some Python dictionaries to map distro names onto package lists. It became somewhat complicated when I tried to support some older Red Hat distros, but it works. I had already put together a module that detects the distro and other things, so it's now all automatic in most cases. But you could make it a manual argument to your installer script, if you want to go that route. 

https://github.com/RedBearAK/toshy/blob/1b495b9b701e93bdaa760646ac224d8a7959fe76/toshy_setup.py#L339

In your case though, you will probably be able to make it into a Flatpak without too much trouble. You're not doing anything particularly weird like messing with device permissions or changing user groups during install.

**Comment by Nyre221** [comment]
Thanks for showing me your script.

For now I've decided to do it this way:
I use "pip install -t ./quick_view_project  qpageview pyexcel etc etc" to install the python modules inside the project folder (no virtual environment) and then create the package as usual.

I tried to create a virtual environment but after it is activated quick view cannot find the libraries present in the system (I suppose it only sees those in the venv). This isn't a problem if you manage to install all the modules, but "python-poppler-qt5" doesn't want to install for some reason (even with a virtual environment). In any case, I guess it's not a problem if it's not completely isolated (i still have to test).

https://gist.github.com/lukassup/cf289fdd39124d5394513a169206631c


> Hey, have you looked at PySide6?

> By 2009, Nokia, the then owners of the Qt toolkit, wanted Python binding available under the LGPL license. Nokia failed to reach an agreement with Riverbank Computing the developers of PyQt Python binding. In August, Nokia released PySide. It provided similar functionality, but under the LGPL

the only reason I didn't use pyside2 (qt5) is that it didn't use the plasma 5 theme when I tried experimenting with it a few months ago. I might make the switch, although I'm not sure of the benefits.

for now I don't think it makes sense to move to qt6 (pyqt6,pyside6) since plasma is still on qt5 and plasma 6 should arrive in February.

**Comment by RedBearAK** [comment]
@Nyre221 

Note: I think GitHub doesn't send out notifications on closed issues unless a mention is included. I knew about this so I came in here and refreshed just in case you'd left a reply. 

> the only reason I didn't use pyside2 (qt5) is that it didn't use the plasma 5 theme when I tried experimenting with it a few months ago. I might make the switch, although I'm not sure of the benefits.

Oh, that might be a good reason not to switch yet. For my app I actually used GPT to help me put a simple light/dark theme in place built-in to the app, since I was actually targeting it at all desktop environments and even thinking of porting it to macOS/Windows. Kind of forgot about that. It was imperfect, but it worked out OK. The main window of the app just shows a color or image, with no window decorations at all. Different situation. 

> I tried to create a virtual environment but after it is activated quick view cannot find the libraries present in the system (I suppose it only sees those in the venv).

Hmm. I'm not expert in Python virtual environments, but from what I understand it just mainly changes the paths in the environment, so that the app looks for its libraries in the `venv` location first. You should still have access to all standard library modules at the system level. Any other dependency should definitely be installed in the `venv`. 

But, I was just using the built-in `venv` module, and there are other ways to make virtual environments that may have different behavior. 

Maybe there should be a new issue about this. I'm sure others with more experience with Python virtual environments will be happy to contribute to the discussion and finding a solution.

**Comment by Nyre221** [comment]
@RedBearAK 

> Hmm. I'm not expert in Python virtual environments, but from what I understand it just mainly changes the paths in the environment, so that the app looks for its libraries in the venv location first. You should still have access to all standard library modules at the system level. Any other dependency should definitely be installed in the venv.

I did some tests with the pyz package and everything works except for python-poppler-qt5 (it doesn't install) and pyqt5 (even when installed it says PyQt5.QtWidgets is missing).

Tomorrow I'm going to make some more changes to the quick view code and then I'll publish it.

Do you think I should change the installation folder? ./config doesn't make much sense.

**Comment by RedBearAK** [comment]
@Nyre221 

> Do you think I should change the installation folder? ./config doesn't make much sense.

Ah, you probably shouldn't ask me about that. I literally have everything installed in `~/.config/toshy`. 🤣  

In fairness to myself everything in my project is tied closely together, and it all has to run from the user's home somehow for cross-display-manager compatibility, and it was a modification of stuff that already worked that way anyway. 

I have noticed that a lot of the "rules" about where code goes in Linux are kind of just conventions. You can always change it up later if the location seems to be causing any kind of issue with your code interacting with or getting used by something else. Besides that, I wouldn't worry about it for now. 

At the very least you made a subfolder instead of just plopping your files in `~/.config`. You've already got a leg up on a lot of KDE apps. 😆  

> I did some tests with the pyz package and everything works except for python-poppler-qt5 (it doesn't install) and pyqt5 (even when installed it says PyQt5.QtWidgets is missing).

I feel like there might be something like an "extras" or "essentials" package that goes along with the main one? Been a while since I was working on that PySide6 app. But you would think `QtWidgets` would be in the base package. 

I've had a lot of trouble with Python imports at times until I do some path tweaking before importing certain things. Hard to say what that's about, other than the specific Python interpreter that gets invoked just can't find what it's looking for in its apparent environment. Um, usually what GPT-4 will tell me is to check things like `sys.path()` to see where it is looking for things. 

Usually it just means you're installing a package to one place, but the Python interpreter is looking somewhere else.
