### ISSUE TITLE
Python virtual environment discussion

### ISSUE THREAD

**Issue by RedBearAK** [Nyre221/dolphin-quick-view#10]
This is a thread for discussing getting Quick View to work with its dependencies installed in a Python virtual environment. 

@Nyre221 

Re: issues with Python interpreter claiming it can't find `PyQt5.QtWidgets` in a virtual environment

In my experience, I can only activate the virtual environment by using a shell script that sources the `bin/activate` script inside the `venv`, and then I can actually run the main Python module and have it start up with the proper environment so that it finds everything installed in the `venv` location. Is that how you're doing it?

**Comment by RedBearAK** [comment]
@Nyre221 

This may or may not have anything to do with anything: 

```sh
#!/bin/python3
```

I have had a tendency to use something more adaptable like this in my shell scripts for a while now: 

```sh
#!/usr/bin/env python3
```

That should mean the Python interpreter from within the virtual environment gets invoked, rather than the interpreter at `/bin/python3`. If you call this module from a shell script that first activates the `venv` before running the Python module. 

But, depending on how you're actually executing the module that contains this shebang line, the shebang line may not have anything to do with anything. 

I have a feeling it may be contributing to your issue in this case.

**Comment by Nyre221** [comment]
> Re: issues with Python interpreter claiming it can't find PyQt5.QtWidgets in a virtual environment

Incorrect, I used "python - m zipapp" to create a .pyz archive with all the libraries inside: https://gist.github.com/lukassup/cf289fdd39124d5394513a169206631c

The problem with this approach is that pyqt5 even if it is installed correctly gives an error when running quick view: module not found: pyqt5.widgets.


>  sources the bin/activate script inside the venv, and then I can actually run the main Python module and have it start up with the proper environment so that it finds everything installed in the venv location. Is that how you're doing it?

yes

For the venv:

> I tried to create a virtual environment but after it is activated quick view cannot find the libraries present in the system (I suppose it only sees those in the venv). This isn't a problem if you manage to install all the modules, but "python-poppler-qt5" doesn't want to install for some reason (even with a virtual environment). In any case, I guess it's not a problem if it's not completely isolated (i still have to test).
> 
simply put: it couldn't find external libraries (python-poppler-qt5 and maybe others)

I don't know if it gives the same problem with PyQt5.QtWidgets

Keep in mind that python-poppler-qt5 cannot be installed either way.

zipapp seems the best to me since there is no need to configure a virtual environment and it can also see the system libraries. the only problem is that pyqt5 is missing libraries and python-poppler-qt5 is not installable.

the virtual environment could have the same problems and moreover it must be configured to make it find the system libraries. 

As an alternative there is also pyinstaller, with which there will probably be no problems with missing libraries (it also takes the system ones). the problem is that it creates gigantic binaries when qt is used and some qt functions don't work well (none in use at the moment). I haven't tried it on this project yet.

**Comment by RedBearAK** [comment]
In case you're not clear on how the virtual environments work, here's some of my understanding: There is a Python interpreter, and a corresponding `pip` binary and some other things that are installed in the `venv` location. You have to make sure you are always invoking the Python binary that lives inside the `venv`, or the results will not be what you expected. 

I've used this to create virtual environments using a newer Python interpreter than the system default, to get my project to work correctly even on systems that still have Python 3.6.x as the main Python version. Like installing Python 3.11 packages on openSUSE Leap and explicitly using the `python3.11` binary to set up the `venv`, instead of `/bin/python3`, which would be 3.6.9 or something. The main part of the project requires at least Python 3.8.6 to work correctly. 

> the virtual environment could have the same problems and moreover it must be configured to make it find the system libraries.

I really don't think that last part is correct. I've never done anything in particular to get my Python modules to have access to the standard library installed at the system level.

**Comment by Nyre221** [comment]
> I really don't think that last part is correct. I've never done anything in particular to get my Python modules to have access to the standard library installed at the system level.

I'll see better tomorrow, I probably did something wrong.

**Comment by RedBearAK** [comment]
GPT-4 is telling me that when the `venv` is created there are either symlinks or copies of the normal "standard library" modules that come with every Python install. So the Python interpreter inside the `venv` is only looking for things inside the `venv`, but that should include all standard Python modules that you would have access to outside the `venv`. 

So the only issue would be additional Python libraries/modules that you've installed at the system level, but can't get installed inside the `venv`. Those won't be available in the `venv`. 

I'd have to see the errors that happen when trying to install the problematic packages in the `venv`. 

I indeed got an error just now attempting to install `python-poppler-qt5` in the `venv` of my own project. I'll have to look into the cause. The error output is not particularly helpful. 

There may be a native "dev" package of some kind that is missing.

**Comment by Nyre221** [comment]
> I'd have to see the errors that happen when trying to install the problematic packages in the venv.

python-poppler-qt5 always fails to install via pip, regardless of where you install it:

[log.txt](https://github.com/Nyre221/dolphin-quick-view/files/12581316/log.txt)

>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: metadata-generation-failed
> 
> × Encountered error while generating package metadata.
> ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip.

**Comment by Nyre221** [comment]
I have a doubt: could it be that pyqt5 with zipapp is not totally included in the application folder because it is installed locally? I'll do a test tomorrow.

however it is probably useless to include pyqt5 if poppler doesn't work. when poppler is installed from apt,dnf,etc, pyqt5 is probably also automatically downloaded (I have to check)

**Comment by RedBearAK** [comment]
>       AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'

This particular error is fixable (I think) by installing `pyqt5-sip`. But the rest of it I haven't made any progress on. I encourage you to file an issue on the GitHub repo for the project. 

It keeps looking for `qmake` but no package on Fedora 38/39 provides `qmake` except a Qt6 devel package, and this complains about the ABI version being wrong when you try to install it with that version of `qmake` installed. 

There are tales all over the web of people having a similar problem with this package, on different platforms. Not many good answers. 

Even `pip install pyqt5-tools` didn't resolve it. 

At this point I'm wondering how you even managed to install it on your system in the first place. 

> however it is probably useless to include pyqt5 if poppler doesn't work. when poppler is installed from apt,dnf,etc, pyqt5 is probably also automatically downloaded (I have to check)

So it came out of a native package? Wonder if all distros will have a similar native package. But that won't help with the virtual environment. 

I'm giving up on it for now.

**Comment by Nyre221** [comment]
> So it came out of a native package? Wonder if all distros will have a similar native package. But that won't help with the virtual environment.

python-poppler-qt5 is installed in this way on every distribution:

https://github.com/Nyre221/dolphin-quick-view/tree/main/Requirements

I believe python-pyqt5 comes pre-installed on some distributions


>however it is probably useless to 
 include pyqt5 if poppler doesn't work. when poppler is installed from apt,dnf,etc, pyqt5 is probably also automatically downloaded (I have to check)

I checked and on manjaro pyqt5 is automatically installed when you install python-poppler-qt5.

For now I think the best solution is to use zipapp. Everything is in one archive and there is no need to activate a virtual environment.

obviously this can be changed later.

With pyisntaller I encountered a problem with gstreamer: `Error: "Could not open resource for reading."`

Pyinstaller would be ideal because it is easy to use and also includes the system libraries and the python interpreter. it works almost like a virtual environment.

Pyinstaller, like a virtual python environment, does not allow the app to find locally installed libraries (even system ones), but this is not a problem since you just need to include them.

**Comment by RedBearAK** [comment]
> python-poppler-qt5 is installed in this way on every distribution:

I hope that holds true for the less common distros. If it's a popular tool, maybe so. It certainly doesn't seem to be maintained well for being installed via `pip`. 

> For now I think the best solution is to use zipapp. Everything is in one archive and there is no need to activate a virtual environment.
> Pyinstaller would be ideal because it is easy to use and also includes the system libraries and the python interpreter. it works almost like a virtual environment.

Anything that you can make work and makes the install simpler and more reliable will be a win. In my own project I only did what was necessary to avoid scaring users with the `--break-system-packages` stuff. 

I got confused by all the installer options for Python apps, partly because I was thinking of making my little image backdrop app cross-platform and some of the options had licensing limitations. But I don't think `pyinstaller` had that kind of issue. I'm probably thinking of Nuitka. 

I really should look into the zippapp thing and see if it's relevant to Toshy.

**Comment by Nyre221** [comment]
> necessary to avoid scaring users with the --break-system-packages stuff.

All the dependencies that I could not include in the .pyz are present in the system repositories (in the tested distributions at least) and therefore no more scary `--break-system-packages`


For example fedora 38 changes from this:
```shell
sudo dnf install python3-qt5 python3-pip antiword python3-poppler-qt5 python3-qpageview gstreamer1-plugin-libav gstreamer1-plugin-openh264 libjpeg-devel ibjpeg-turbo-devel

pip install pyexcel pyexcel-xls pyexcel-xlsx textract
``` 

to this:
```shell
sudo dnf install python3-qt5  antiword python3-poppler-qt5  gstreamer1-plugin-libav gstreamer1-plugin-openh264 libjpeg-devel ibjpeg-turbo-devel

``` 

Look here: https://github.com/Nyre221/dolphin-quick-view/tree/main/package%20creation

**Comment by RedBearAK** [comment]
Yes, looks like a good improvement. But FYI it looks like a typo snuck into your package list: 

```sh
ibjpeg-turbo-devel
```

I'm not sure if `libjpeg-turbo-devel` is necessary to name directly, but it does show up as a package whereas I think `libjpeg-devel` is a meta-package that just make sure `libjpeg-turbo-devel` gets installed. At least on Fedora 38. Probably safest to keep both like you have there on the list.

**Comment by Nyre221** [comment]
> Probably safest to keep both like you have there on the list.

I included it for exactly this reason.

Regarding python-poppler-qt5:

After installing some libraries the installation continued until:

```shell
Defaulting to user installation because normal site-packages is not writeable
Collecting python-poppler-qt5
  Using cached python-poppler-qt5-21.3.0.tar.gz (28 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Querying qmake about your Qt installation...
      These bindings will be built: Poppler-Qt5.
      Generating the Poppler-Qt5 bindings...
      Generating the .pro file for the popplerqt5 module...
      Generating the top-level .pro file...
      Generating the Makefiles...
      Compiling the project...
      Installing the project...
      _in_process.py: 'make install' failed returning 2
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.

``` 


these are the libraries I installed on kde neon:
```
sudo apt install libpoppler-qt5*
sudo apt install pyqt5-dev
```
I need to investigate why `make` exits with code 2.

From what I've read, I need to install  `build-essential` but it is already installed (ubuntu distro only).

Hmmm, https://codeforgeek.com/make-failed-with-exit-code-2/#:~:text=Generally%2C%20the%20%E2%80%9Cmake%20failed%20with,module%20you%20tried%20to%20install.

I'll try to resolve it tomorrow.

**Comment by RedBearAK** [comment]
The install process is pretty clean now in F38, but there are some deprecation warnings. In some terminals these are orange and may make users think the install had a problem. They should be avoidable if you `pip install wheel`, but I'm not sure if you need to get `wheel` installed first or if it will get installed by `pip` first if it's part of a group of packages, and still be able to cancel the deprecation warnings. 

There may also be native packages to get it installed, like the `python3-wheel` package on F38. 

In my own package I ended up doing a sequence of things during the `pip` install phase in the `venv`, just to minimize the number of "complaints" the users would see in the terminal: 

```py
    commands        = [
        [venv_python_cmd, '-m', 'pip', 'install', '--upgrade', 'pip'],
        [venv_pip_cmd, 'install', '--upgrade', 'wheel'],
        [venv_pip_cmd, 'install', '--upgrade', 'setuptools'],
        [venv_pip_cmd, 'install', '--upgrade', 'pillow'],
        [venv_pip_cmd, 'install', '--upgrade'] + filtered_pip_pkgs
    ]
```

So, `pip` upgrades itself using the recommended syntax, then I get `wheel` and `setuptools` (and `pillow`, for some reason) installed, then I dump the rest of the `pip` package list in there. That sequence has seemed to work out pretty well for my use case. Generally if I get the native package list correct for the distro, the `pip` installs have no errors or warnings of any kind now. 

Also the typo is still in the requirements text file for F38. Sorry to bring that up again if you're waiting to fix that when you do a new big commit or something. 

```sh
ibjpeg-turbo-devel
```

**Comment by Nyre221** [comment]
> Also the typo is still in the requirements text file for F38. Sorry to bring that up again if you're waiting to fix that when you do a new big commit or something.

I've fixed the error now that I've updated the requirements.

@RedBearAK 

So you managed to install python-poppler-qt5 in a venv, right?

I didn't notice your message before and I released the zipapp version...
Next time I will use the virtual environment.

Thanks for your help.

**Comment by RedBearAK** [comment]
> So you managed to install python-poppler-qt5 in a venv, right?

Nope, and I don't know why you would think that. I gave up on that, especially after you said it's always available as a native package. 

I was just using your latest instructions in the text file for F38. (from before the 1.2 release)
