### ISSUE TITLE
`qdbus` command is sometimes `qdbus-qt5`

### ISSUE THREAD

**Issue by RedBearAK** [Nyre221/dolphin-quick-view#11]
@Nyre221 

In my project, while trying to make it as widely compatible as possible, I ran into at least one Linux distro where the `qdbus` command was not found, and instead was available as `qdbus-qt5`. 

I ended up having to use `shutil.which()` to check whether either was available, and set a variable to use as an abstraction so the correct command name would be used. 

This is from a class `init` method where I set up the class attribute to use in other places in the installer script: 

```py
        self.qdbus                  = 'qdbus-qt5' if shutil.which('qdbus-qt5') else 'qdbus'
```

My installer has been okay ever since I implemented that. 

Might want to keep this on the back burner to work on at some point.

**Comment by RedBearAK** [comment]
I wasn't paying enough attention. The usage of `qdbus` was in a Bash script, so the Python stuff I was talking about would be irrelevant. You'd have to do command checks the Bash way, more like this: 

```sh
# Get out of here if systemctl is not available
if command -v systemctl >/dev/null 2>&1; then
    # systemctl is installed, proceed
    :
else
    # no systemctl found, exit silently
    exit 0
fi
```

This is how I check to see if the `systemctl` command is available before I try to use it from some Bash scripts. The colon is the Bash equivalent of a "no op" or `pass` in Python.

**Comment by Nyre221** [comment]
@RedBearAK 
I'm currently using "dbus-send" and not the "qdbus" command.

I could be wrong but I don't think dbus-send can change name depending on the distribution: https://www.freedesktop.org/wiki/Software/dbus/

I can still implement some checks and error messages, but it's really a low priority at the moment.

edit:

I have to put checks in other parts too, so for now I don't want to focus on something so specific.

**Comment by Nyre221** [comment]
@RedBearAK 
I used your code on the shortcut and I also introduced some checks on the installation script.

Thanks for the help.

**Comment by RedBearAK** [comment]
@Nyre221 

Yeah, I don't expect `dbus-send` to ever have a different name, but it's always best practice to check that any command exists before attempting to use it, so good to have it in there anyway. 

>  I used your code on the shortcut and I also introduced some checks on the installation script.

Excellent. I'll go ahead and close this.
