### ISSUE TITLE
(enh) Installer script rework suggestion

### ISSUE THREAD

**Issue by RedBearAK** [Nyre221/dolphin-quick-view#13]
@Nyre221 

I have a suggested rework of the installer script, not really to change what it does but mainly to change how it presents itself and handles errors. One reason is to have it integrate fairly cleanly with my own project, as an optional install component on KDE. 

Take a look and if you like it I can submit it as a PR. But I thought I'd ask you first if you are good with the style changes I did, or if you want to do something more minimal. 

https://github.com/RedBearAK/dolphin-quick-view/blob/installer_script_rework/package%20creation/quick_view_package/INSTALL.sh

**Comment by Nyre221** [comment]
> Take a look and if you like it I can submit it as a PR. But I thought I'd ask you first if you are good with the style changes I did, or if you want to do something more minimal.  

I took a look at the changes and I really like how you improved it. The only thing I don't like is the error message for gdbus: ` echo "WARNING: The 'gdbus' command was not found. Cannot display success notification."`

A message like this might make users think that it is something necessary for quickview:https://github.com/Nyre221/dolphin-quick-view/issues/6  

It would be better to put a less worrying notification or remove it completely. If you agree, I will accept your PR request.



Thanks for the help!

**Comment by RedBearAK** [comment]
Question: Do you show the notification in case the user runs the installer by double-clicking on it in the file manager? 

If that’s the purpose, I can set it up to fall back on trying things like `notify-send` and then have it show a more innocuous info message if nothing is available. Making it clear that it only pertains to the installer.

**Comment by Nyre221** [comment]
> Question: Do you show the notification in case the user runs the installer by double-clicking on it in the file manager?

yes, that was the idea.

>    I can set it up to fall back on trying things like notify-send and then have it show a more innocuous info message if nothing is available.

it would be perfect.

Thanks again.

**Comment by RedBearAK** [comment]
OK, you should be able to go to the same link, refresh and see the changes. If you like it I'll copy-pasta it into a new PR so it just comes in as a single commit. There are several commits as it is. 

I made it cascade through `gdbus`, `notify-send` and `kdialog`, using the first available command. Each retains the 5-second timeout and proper icon. The "INFO:" message will show only if all three commands are missing, which should be basically impossible. 

Tested good in the VM, by disabling each option, and then all options, with invalid characters in the command name(s).

**Comment by Nyre221** [comment]
> I made it cascade through gdbus, notify-send and kdialog, using the first available command. Each retains the 5-second timeout and proper icon. The "INFO:" message will show only if all three commands are missing, which should be basically impossible.

Really nice work!

>  There are several commits as it is.

I don't think it changes anything, right? 
When you are ready you can make the pool request and I will accept it.

Thanks again

**Comment by RedBearAK** [comment]
Submitted as PR #14.

**Comment by Nyre221** [comment]
> Submitted as PR https://github.com/Nyre221/dolphin-quick-view/pull/14.

Merged
