### ISSUE TITLE
Aspect ratio not respected?

### ISSUE THREAD

**Issue by khawkins98** [Nyre221/dolphin-quick-view#15]
New to this program (it's nice, thanks!).

Issue I'm having is that the aspect ratio isn't respected for media (PDF, Images, videos) and is always stretched too wide.

This is on the new 1.2.3 release (I've not had experience with the older ones).

![image](https://github.com/Nyre221/dolphin-quick-view/assets/928100/f6f337e6-6e1a-4981-b436-9f896c9a0811)

## KDE system info

```
Operating System: Manjaro Linux 
KDE Plasma Version: 5.27.8
KDE Frameworks Version: 5.110.0
Qt Version: 5.15.10
Kernel Version: 6.5.3-1-MANJARO (64-bit)
Graphics Platform: Wayland
Processors: 8 × 11th Gen Intel® Core™ i5-1130G7 @ 1.10GHz
Memory: 15,4 GiB of RAM
Graphics Processor: Mesa Intel® Xe Graphics

```

**Comment by Nyre221** [comment]
On a clean install of manjaro this doesn't happen.
Have you installed all the dependencies?    
`sudo pacman -S python-pyqt5 python-poppler-qt5`

If installing the dependencies didn't work, try applying the original plasma (breeze) style.

If nothing changes, try this command and tell me if you see any errors:` ~/.config/quick_view/quick_view.pyz /path/to/some/file  -s`
