### ISSUE TITLE
Support viewing krita's kra file 

### ISSUE THREAD

**Issue by raghu-kamath** [Nyre221/dolphin-quick-view#18]
Krita's native file format is a zip file under the hood. It contains a preview.png for small thumbnails and a mergedimage.png for high resolution full size image of the file inside. So we can use this mergedimage.png file to get the file preview of kra files.

So I request you to add support for kra file preview it will be good to see kra document preview when browing large folder of artworks.

**Comment by Nyre221** [comment]
@raghu-kamath 
Hi, I released a new version with .kra support.
Let me know if there are any problems.

**Comment by raghu-kamath** [comment]
I will check this out, really thanks for quick reply 🙏
