### ISSUE TITLE
[HELP] How can I uninstall the plugin?

### ISSUE THREAD

**Issue by matheusunderline** [Nyre221/dolphin-quick-view#20]
Hi, there. :wave: 

First, thank you Nyre221 for the nice plugin. :partying_face: 

Sorry to silly ask...

***Could you tell me how can I uninstall your plugin, please? In order to reinstall the plugin, if it for need.***

Thank you in advance. :heart:

**Comment by Nyre221** [comment]
Hi, to remove it you just need to delete  ` ~/.config/quick_view/` and `~/.local/share/kservices5/ServiceMenus/quick_view.desktop`.

**Comment by matheusunderline** [comment]
All right, thank you so much for answer and speed, :pray: !
