### ISSUE TITLE
Is there an intention to migrate to Qt6 ?

### ISSUE THREAD

**Issue by luzpaz** [Nyre221/dolphin-quick-view#22]
KDE is in the process of migrating (along with many other FLOSS projects) to Qt6. Is that on the roadmap ?

**Comment by Nyre221** [comment]
@luzpaz 
Yes, there will be a qt6 version.  
I've been a little busy and will start it at the beginning of next month.

Thanks for your interest.

**Comment by guiodic** [comment]
meanwhile, on plasma 6 the video doesn't work...

**Comment by Nyre221** [comment]
@luzpaz  @guiodic 
What distribution are you using?


> meanwhile, on plasma 6 the video doesn't work...

What graphic card and driver are you using?
I noticed that in the Qt6 version if you have nvidia you need the proprietary driver to load the videos.

The Qt6 version is almost finished, all that remains is to check a few things and see what dependencies are required in the various distributions.

**Comment by guiodic** [comment]
I use Arch, intel iGPU.

**Comment by Nyre221** [comment]
@guiodic  @luzpaz 

https://github.com/Nyre221/dolphin-quick-view/releases/tag/v1.2.7_RC1

https://github.com/Nyre221/dolphin-quick-view/tree/main/Requirements/Plasma%206

**Comment by guiodic** [comment]
it works, thank you!

I remember in the previous version I was able to enlarge the window which is a bit small by default, but I don't remember how I did it, is there a configuration file?

**Comment by guiodic** [comment]
p.s. is kiview intended to replace dolphin-quick-view?

**Comment by Nyre221** [comment]
@guiodic 

https://github.com/Nyre221/dolphin-quick-view/blob/main/quick_view.py line 44

```
    self.resize(int(screen_size.width() * 0.5),
                    int(screen_size.height() * 0.55))
```
There is no configuration file currently.

maybe you can also do it with a kwin window rule.


> p.s. is kiview intended to replace dolphin-quick-view?

it was, but C++ is much harder and I'm not sure what to do. 
For now I'll try to port it to Qt6 and then I'll see if it's worth keeping it updated.

**Comment by Nyre221** [comment]
@guiodic 

https://github.com/Nyre221/dolphin-quick-view/releases/tag/v1.2.7_RC3

the window size is now restored on startup.

**Comment by guiodic** [comment]
Hi, the RC2 version retains the size (thank you!) but is not placed in the center of the screen. Would it be possible to keep it there all the time?

**Comment by Nyre221** [comment]
@guiodic 
I prefer not to save or set the position because it could cause problems with those who have two or more screens.

Kwin in my case already automatically places the window in the center of the screen every time, so I think it's more of a configuration issue:

![Schermata_20240402_153052-1](https://github.com/Nyre221/dolphin-quick-view/assets/104171042/3a1415dc-c656-4718-bfcc-b68e187bf288)



Another solution is to use a window rule:
1) Open QuickView
2) ALT+F3
3) More actions
4) Click on "Configure Special Window Settings" or "Configure Special Application Settings"
5) Add properties
6) Search for "Position"
7) Apply

**Comment by Cherkah** [comment]
i prefer to post here as the topic is the quite the same
can you update the AUR (arch) version which is i.2.6 ?

regards

**Comment by Nyre221** [comment]
@Cherkah 
> i prefer to post here as the topic is the quite the same
> can you update the AUR (arch) version which is i.2.6 ?

Hi, I'm not the maintainer of the AUR package and I can't update it.

If you want the updated version you can download it from the releases section and use the same dependencies for endevourOS:

https://github.com/Nyre221/dolphin-quick-view/tree/main/Requirements/Plasma%206
https://github.com/Nyre221/dolphin-quick-view/releases
