### ISSUE TITLE
dolphin-quick-view & plasmsa-desktop

### ISSUE THREAD

**Issue by gleyconJ** [Nyre221/dolphin-quick-view#23]
Hello!
I would like to know if there is a way for this add-on to work directly on the Plasma desktop. Or using the "Folder View" plasmoid. Because the shortcut in the context menu exists, however, when I click on it nothing happens. But if I do the same thing within the Dolphin application, then it works normally.

How do I get this to work on the Plasma desktop?

**Comment by Nyre221** [comment]
@gleyconJ 
Hi, there is currently no way to make this work on the desktop or via the folder plasmoid. QuickView uses dolphin's Dbus calls to work and at the moment the way it integrates is more of a hack than a clean way. 

This is more up to the plasma developers, I can't do much.

Have a nice day

**Comment by gleyconJ** [comment]
I understand, but at some point, have you tried to contact them asking if they could open the way in the plasma for you to implant something like that? Or can I immediately give up this functionality in Plasma 6?

**Comment by Nyre221** [comment]
@gleyconJ 

At the moment I'm more focused on recreating QuickView in C++: https://github.com/Nyre221/Kiview

I've talked to some developers about the possibility of making changes to dolphin for better integration and the possibility of making Kiview an official application, but I haven't made a direct request yet.
Before making such a request I would like to have a better idea of what is actually needed (in the case of dolphin).

>  Or can I immediately give up this functionality in Plasma 6?

I don't think desktop integration will be something that will happen in the near future (if there ever will be).
