### ISSUE TITLE
Does it work with Pop_os ?

### ISSUE THREAD

**Issue by tiger360** [Nyre221/dolphin-quick-view#24]
Hi there! I recently came across your dolphin-quick-view project and was eager to try it out on my Pop_OS system. Unfortunately, I've encountered some challenges during the installation process, and it seems that the application may not be compatible with Pop_OS.

Thanks

**Comment by Nyre221** [comment]
@tiger360 

Are you using kde plasma?
Quick view only works on plasma5/6 and with the dolphin file manager, for Gnome you can try Gnome sushi: https://ubuntuhandbook.org/index.php/2022/07/gnome-sushi-quickly-preview-files/

The latest version of Quick View compatible with Plasma 5 is the 1.2.6:
https://github.com/Nyre221/dolphin-quick-view/releases/tag/v1.2.6

requirements: https://github.com/Nyre221/dolphin-quick-view/tree/main/Requirements

I have also developed a new version in C++ which will soon be released as a flatpak:
https://github.com/Nyre221/Kiview
