### ISSUE TITLE
Office documents 

### ISSUE THREAD

**Issue by guiodic** [Nyre221/dolphin-quick-view#8]
Hi, thank you for Quick View, lo aspettavo da anni!
I would suggest, for Office documents (both libreoffice and MS Office) to convert them to PDF and display them. unoconv can be useful for this.
In any case, I cannot get the display of xls(x) files, ods, ppt etc. to work while doc(x) files are displayed as plain text.

**Comment by Nyre221** [comment]
Sono felice che sia di utilità a qualcuno :)

> I would suggest, for Office documents (both libreoffice and MS Office) to convert them to PDF and display them. unoconv can be useful for this.

This is actually something I had already tried to do (before releasing on github) and the results were disappointing.
There are two problems with this approach:
1) requires libreoffice installed locally, and in addition unoconv, besides not being necessary (better to create a small class and not add another dependency), doesn't even work with the flatpak version of libreoffice.
2) it is extremely slow to convert to pdf (biggest problem)

the slowness is the worst part.

I tried converting to html and markdown (faster), but unfortunately the formatting is completely broken (gigantic images, missing graphs, etc) and so I decided to simply extract the text (the tables are readable this way).

For odt (I don't think it can be done for xls/xlsx), the solution would be to create a class that extracts the data from the odt archive and formats it in a decent way.


> In any case, I cannot get the display of xls(x) files, ods, ppt etc. to work while doc(x) files are displayed as plain text.

what distro are you using?
you don't have pyexcel installed (pyexcel pyexcel-xls pyexcel-xlsx ).
ppt are not supported.

https://github.com/Nyre221/dolphin-quick-view/tree/main/Requirements


I'm closing this report.

It's not a good thing to have multiple reports mixed into one: it creates confusion and is more difficult to help.

You can open another report if you still have problems.
